[package]
name = "ux-components"
version = "0.1.0"
authors = ["Victor Dudochkin <dudochkin.victor@gmail.com>"]
readme = "README.md"
homepage = "https://angular-rust.github.io/ux-components"
repository = "https://github.com/angular-rust/ux-components"
documentation = "https://docs.rs/ux-components"
description = "Backend agnostic GUI framework"
keywords = ["wasm", "web", "material-design", "material-components", "gtk"]
categories = ["wasm", "web-programming", "gui"]
edition = "2018"
license = "MPL-2.0"

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "components"

[features]
web = ["wasm-bindgen", "wasm-bindgen-futures", "wasm-logger", "gloo", "js-sys", "wasm-bindgen-test", "web-sys"]
cairo = ["cairo-rs"]
default = ["cairo"]

[dependencies]
log = "0.4"
cairo-rs = { version = "0.9", optional = true }

bitflags = "1.0"

atk = "0.9"
glib-sys = "0.10"
gdk-sys = "0.10"
gio-sys = "0.10"
gobject-sys = "0.10"
cairo-sys-rs = "0.10"
gdk-pixbuf = "0.9"
gio = "0.9"
glib = "0.10"
pango = "0.9"
x11 = "2.18"

cogl-rs = "0.1.3"
clutter-rs = "0.1"
ruex = "0.1"
ux-macro = "0.1"
ux-primitives = "0.1"
ux-dataflow = "0.1"
ux-animate = { version = "0.1", features = ["cairo"] }
ux-charts = { version = "0.1", features = ["cairo"] }

# starup notifications
notify-rust = "4"

wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
wasm-logger = { version = "0.2", optional = true }
gloo = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }
wasm-bindgen-test = { version = "0.3", optional = true }
simplecss = "0.2"

[dependencies.web-sys]
version = "0.3"
optional = true
features = [
  'KeyboardEvent',
  "ValidityState",
  "CustomEvent",
  "Node",
  "Element",
  "HtmlElement",
  "Window",
  "Document",
]

[dev-dependencies]
